# Database connection
spring.datasource.url=jdbc:postgresql://ep-floral-feather-a1p2eq2t-pooler.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_25LygGOcBxRX
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server port (optional)
#server.port=8080
#server.port=${PORT:10000}
server.port=10000

jwt.secret.key=thisisadityasecretkeywhichissecure123456



#9.04.11
razorpay.key.id=

razorpay.key.secret=

#spring.servlet.context-path=/api/v1            